### ISSUE TITLE
Yulp Contract deployement

### ISSUE THREAD

**Issue by usamagujjar1122** [libevm/subway#17]
I am facing lots of issues in deploying yulp contract to etherium chain. Can you code and publish a solidity contract?

**Comment by libevm** [comment]
skill issue

**Comment by usamagujjar1122** [comment]
I don't think soo! 
I compiled with npm run compile in src/contracts . I created a deploy.js file that uses .abi and .bytecode from "out" folder to deploy to etherium chain.
It returns error INVALID ABI. 
When I replaces abi with [], Contract was deployed but transactions are always reverted.
I searched for contracts with similar bytecode on etherium chain and  found 3 contracts. None of them succeed in performing even a single transaction.
Also one contarct from them deposited 0.01WETH but failed to transact function recoverETH.

Shall we transfer funds to contract to make it work?

Also I switched logic from sandwich contract to directly buying from my wallet. Bundle was submitted to flasbot but no transactions were actually peroformed.

Can you ellaborate?

**Comment by htkcodes** [comment]
u have a skill issue.. get gud.

**Comment by mgmarltd** [comment]
get gut.
