### ISSUE TITLE
Missing variables despite them all being filled in...

### ISSUE THREAD

**Issue by Astraioss** [libevm/subway#2]
`yarn bot

yarn run v1.22.17

$ node index.js

Missing env var RPC_URL

Missing env var RPC_URL_WSS

Missing env var PRIVATE_KEY

Missing env var FLASHBOTS_AUTH_KEY

Missing env var SANDWICH_CONTRACT
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by htkcodes** [comment]
fill the .env with the missing variables. You probably shouldn't try to run things on the internet if you can't read code or before reading the code.

**Comment by libevm** [comment]
Answered by @htkcodes

**Comment by Astraioss** [comment]
> fill the .env with the missing variables. You probably shouldn't try to run things on the internet if you can't read code or before reading the code.

Oh haha maybe you shouldn't be sarcastic without understanding that I've obviously filled in those missing variables and it still gives me that error ...

**Comment by htkcodes** [comment]
> > fill the .env with the missing variables. You probably shouldn't try to run things on the internet if you can't read code or before reading the code.
> 
> Oh I've read the code and filled in those missing variables (read title of issue) and it still gives me that error. I must've just filled one of them in wrong tbh... You don't need to be rude about it

Do this

`js
import { dirname } from 'path';
import { fileURLToPath } from 'url';
const __dirname = dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: `${__dirname}/.env` });
`
