### ISSUE TITLE
Is the math in getUniv2DataGivenIn incorrect?

### ISSUE THREAD

**Issue by mmarkell** [libevm/subway#3]
We are calculating newReserveA as being reserveA + aInWithFee, but aInWithFee is 997 times too big, no?
```js
export const getUniv2DataGivenIn = (
  aIn,
  reserveA,
  reserveB
) => {
  const aInWithFee = aIn.mul(997);
  const numerator = aInWithFee.mul(reserveB);
  const denominator = aInWithFee.add(reserveA.mul(1000));
  const bOut = numerator.div(denominator);

  // Underflow
  let newReserveB = reserveB.sub(bOut);
  if (newReserveB.lt(0) || newReserveB.gt(reserveB)) {
    newReserveB = ethers.BigNumber.from(1);
  }

  // Overflow
  let newReserveA = reserveA.add(aInWithFee); // this is 997 times too big?
  if (newReserveA.lt(reserveA)) {
    newReserveA = ethers.constants.MaxInt256;
  }

  return {
    amountOut: bOut,
    newReserveA,
    newReserveB,
  };
};

```

**Comment by htkcodes** [comment]
Should it be..

`javascript
let newReserveA = reserveA.add(aIn);
`

**Comment by mmarkell** [comment]
You have to subtract the 3% fee right? so reserveA.add(aIn * .97)

**Comment by mmarkell** [comment]
so 
```
let newReserveA = reserveA.add(aInWithFee.div(1000))
```

**Comment by htkcodes** [comment]
```javascript
  public getOutputAmount(inputAmount: CurrencyAmount<Token>): [CurrencyAmount<Token>, Pair] {
    invariant(this.involvesToken(inputAmount.currency), 'TOKEN')
    if (JSBI.equal(this.reserve0.quotient, ZERO) || JSBI.equal(this.reserve1.quotient, ZERO)) {
      throw new InsufficientReservesError()
    }
    const inputReserve = this.reserveOf(inputAmount.currency)
    const outputReserve = this.reserveOf(inputAmount.currency.equals(this.token0) ? this.token1 : this.token0)
    const inputAmountWithFee = JSBI.multiply(inputAmount.quotient, _997)
    const numerator = JSBI.multiply(inputAmountWithFee, outputReserve.quotient)
    const denominator = JSBI.add(JSBI.multiply(inputReserve.quotient, _1000), inputAmountWithFee)
    const outputAmount = CurrencyAmount.fromRawAmount(
      inputAmount.currency.equals(this.token0) ? this.token1 : this.token0,
      JSBI.divide(numerator, denominator)
    )
    if (JSBI.equal(outputAmount.quotient, ZERO)) {
      throw new InsufficientInputAmountError()
    }
    return [outputAmount, new Pair(inputReserve.add(inputAmount), outputReserve.subtract(outputAmount))]
  }
  ```
  i just looked and how uniswap does in their sdk and they seem to just add the inputamount to the reserve

**Comment by mmarkell** [comment]
Yeah but inputAmount wasn't multiplied by 997 @htkcodes . Compared to in this project

**Comment by htkcodes** [comment]
> Yeah but inputAmount wasn't multiplied by 997 @htkcodes . Compared to in this project

```javascript
const inputAmountWithFee = JSBI.multiply(inputAmount.quotient, _997)
```

same thing

**Comment by mmarkell** [comment]
When they return the new reserve amount, they add inputAmount, not inputAmountWithFee.

**Comment by libevm** [comment]
Code is referencing `UniswapV2Library.sol`

https://github.com/Uniswap/v2-periphery/blob/master/contracts/libraries/UniswapV2Library.sol#L43

Try calculating the reserves by hand and compare to the output

**Comment by htkcodes** [comment]
Yes so input amount in @libevm project is "aIn". Its the same thing

**Comment by jtsiskin** [comment]
> Code is referencing `UniswapV2Library.sol`
> 
> https://github.com/Uniswap/v2-periphery/blob/master/contracts/libraries/UniswapV2Library.sol#L43
> 
> Try calculating the amount outs given reserves by hand and compare to the output obtained by the router

@libevm the amount out is correct. The reserveA update is not. amountInWithFee is 1000x larger than the actual reserve update, no? Uniswap just doesn't name its variables `amountInWithFeeTimes1000` even when they are

**Comment by mmarkell** [comment]
Right exactly ^^

**Comment by mmarkell** [comment]
@htkcodes I agree that input amount is the same, but the newly calculated reserves are different.

**Comment by htkcodes** [comment]
> @htkcodes I agree that input amount is the same, but the newly calculated reserves are different.

So i think this should be the fix no?
```javascript
let newReserveA = reserveA.add(aIn);
```
Just like the sdk's

**Comment by libevm** [comment]
> @libevm the amount out is correct. The reserveA update is not. amountInWithFee is 1000x larger than the actual reserve update, no? Uniswap just doesn't name its variables amountInWithFeeTimes1000 even when they are

@jtsiskin  No need for the passive aggressiveness -- I gain nothing open sourcing this

@mmarkell I see, nice find. PRs welcomed!

**Comment by mmarkell** [comment]
Hmm @libevm when I try to push a PR branch, it says access denied. Do you need to update settings?

**Comment by libevm** [comment]
@mmarkell you'll need to fork it, then make a PR from your fork

**Comment by mmarkell** [comment]
Oh I see

**Comment by libevm** [comment]
Closed https://github.com/libevm/subway/pull/4
