### ISSUE TITLE
Remove Flashbots

### ISSUE THREAD

**Issue by throwthatbrick** [libevm/subway#5]
I changed some code around and so far its running on AVAX, but I'm curious about how I'd go about removing the Flashbots functions without breaking the entire bot. Do you have any pointers?

**Comment by brendanwenzel** [comment]
You need to write your own transaction functions to complete the swaps. 

The Flashbots part is only used for carrying out the transactions at the end. You can remove all references to it and replace it relatively easily.

**Comment by atropos0902** [comment]
I have the same issue.
I wanna run this on `BSC` but flashbot doesn't support `BSC`.
So I cannot simulate the bundles and send those bundles.
What's the solution?

**Comment by atropos0902** [comment]
@throwthatbrick 
Did you find any solution on `AVAX`?

**Comment by atropos0902** [comment]
> You need to write your own transaction functions to complete the swaps.
> 
> The Flashbots part is only used for carrying out the transactions at the end. You can remove all references to it and replace it relatively easily.

How?
With what can it be done easily like you said?
