### ISSUE TITLE
weth and token in payloads looks switched. I think it should be the other way around

### ISSUE THREAD

**Issue by nardis556** [libevm/subway#7]
https://github.com/libevm/subway/blob/8ea4e86c65ad76801c72c681138b0a150f7e2dbd/bot/index.js#L163

**Comment by htkcodes** [comment]
Its fine.

**Comment by sewinter** [comment]
How are they not switched? Frontrun should be weth => token; backrun should be token => weth. @htkcodes @nardis556

**Comment by htkcodes** [comment]
> How are they not switched? Frontrun should be weth => token; backrun should be token => weth. @htkcodes @nardis556 

The issue was closed no? the correct order is already there

**Comment by sewinter** [comment]
I don't think it should have been closed, as `token` is still in the frontslice tx payload instead of `weth`? Maybe I'm misunderstanding something though?

**Comment by htkcodes** [comment]
> I don't think it should have been closed, as `token` is still in the frontslice tx payload instead of `weth`? Maybe I'm misunderstanding something though?

If weth is in the frontslice.. you'd be buying weth with weth? that's not possible.. the token is in the frontslice which tells the contract which token to buy..

**Comment by sewinter** [comment]
I think that the token in the payload is the token that's being sold, as it's the one being transferred to the pair:

https://github.com/libevm/subway/blob/master/contracts/src/Sandwich.sol#L77-L86

**Comment by htkcodes** [comment]
> I think that the token in the payload is the token that's being sold, as it's the one being transferred to the pair:
> 
> https://github.com/libevm/subway/blob/master/contracts/src/Sandwich.sol#L77-L86

![Screenshot_20220824-173511_GitHub.jpg](https://user-images.githubusercontent.com/26159611/186536630-4fac0b10-88a4-4678-a15f-d8ad133506dc.jpg) this my implementation

**Comment by htkcodes** [comment]
As you can see the order is correct

**Comment by sewinter** [comment]
In the code you linked, it's transferring wbnb/weth to the pair, so it's selling wbnb/weth, but in the excerpt I linked that's in this repo, it's transferring the non-weth token in the frontrun tx, so it's actually selling non-weth first.

**Comment by htkcodes** [comment]
> In the code you linked, it's transferring wbnb/weth to the pair, so it's selling wbnb/weth, but in the excerpt I linked that's in this repo, it's transferring the non-weth token in the frontrun tx, so it's actually selling non-weth first.

no brother.. if you're transferring wbnb/weth to the pair you're buying.

**Comment by sewinter** [comment]
> > In the code you linked, it's transferring wbnb/weth to the pair, so it's selling wbnb/weth, but in the excerpt I linked that's in this repo, it's transferring the non-weth token in the frontrun tx, so it's actually selling non-weth first.
> 
> no brother.. if you're transferring wbnb to the pair you're buying.

Right, I agree. In your code it's transferring/selling wbnb and buying some other token, but in this repo, I think it's instead transferring the non-weth token first, so it's buying weth in the frontrun instead of selling it.

**Comment by sewinter** [comment]
Also I appreciate you digging into this with me!

**Comment by htkcodes** [comment]
You maybe right actually.. i didnt test the assembly one because frankly i didn't understand it so well. so i rewrote it the "regular" way.. but from what im seeing it seems to be reversed..but im not sure tbh.. assembly isnt my forte.. but works well with my rewrite tho

**Comment by sewinter** [comment]
Thanks, I'm glad it's not just me. Thought I was maybe misunderstanding something reading it.

**Comment by htkcodes** [comment]
> Thanks, I'm glad it's not just me. Thought I was maybe misunderstanding something reading it.

https://github.com/libevm/subway/issues/7#issuecomment-1226588384

here's my rewrite if u wanna check it out - https://gist.github.com/htkcodes/e75c3ff7188ad9d7b190a042074f9cde

**Comment by sewinter** [comment]
Thanks, that's super helpful!

**Comment by nardis556** [comment]
yeah @sewinter. sorry for closing 😄
